### ISSUE TITLE
Closest Emacs theme to reddit-emacs-css?

### ISSUE THREAD

**Issue by priyadarshan** [alphapapa/reddit-emacs-css#1]
Thank you for the new `reddit-emacs-css`.

I like it so much that I would like to use an Emacs theme as close as possible to it. Would you have any suggestions?

Thanks again,  [/r/emacs ](https://www.reddit.com/r/emacs) looks über-cool now!

**Comment by alphapapa** [comment]
Oh, hi there.  :)  Sorry, GitHub's notification system makes it hard to keep up with bugs in your own repos, because they don't show up in "Participating" unless you have already seen and acted on an issue.  :(

I'm glad you like the theme.  Don't forget Nicolas Petton, who actually designed the theme; I just implemented it for Reddit's CSS.

I would say that the closest theme for Emacs that I know of would be Solarized Light.  It's not quite the same though, as it's more yellow than the beige/sandy color the Emacs site uses.  But I like the idea of having an Emacs theme that resembles the new Emacs web site!  That's a really good idea.  I've never made an Emacs theme before, but maybe I'll give it a try sometime...

By the way, you might find this interesting: http://github.com/alphapapa/solarized-everything-css  Again, it's Solarized Light, not the Emacs web site theme, but you might still like it.  I use the Solarized Light style on GitHub, and I really like it a lot better than the default GitHub theme.

**Comment by priyadarshan** [comment]
Thank you, I thought it was looking similar to solarized-light, but personally, I find your work on /r/emacs somehow better, perhaps the contrast is more suitable for me. Thank for pointing to solarized-everything-css. Is it available on userstyles.org?

**Comment by alphapapa** [comment]
No, I haven't submitted it there, but I guess that's a good idea.  I'll have to look into it.  Thanks.

...

I just posted the GitHub styles up there, that wasn't too hard: https://userstyles.org/styles/127328/github-solarized

**Comment by priyadarshan** [comment]
> I just posted the GitHub styles up there, that wasn't too hard: https://userstyles.org/styles/127328/github-solarized

It looks wonderful, thanks!
