### ISSUE TITLE
unvisited links are indistinguishable from visited ones

### ISSUE THREAD

**Issue by ajarara** [alphapapa/reddit-emacs-css#2]
it's bothered me, [and others](https://www.reddit.com/r/emacs/comments/4cq8sb/suggestion_box/d2djtr7), for quite some time. yes we can disable sub CSS, yes we can install extensions, but this setting confuses newcomers and those of us who like the theme and dislike installing extensions unless absolutely necessary.

The offending rule is here:
`a, .search-expando-button  {
    color: #76319F !important;
}`

can it be removed, or at least changed? blue links look just fine on the bg when I disable this rule.

**Comment by alphapapa** [comment]
Hi,

Hm, that's a good point.  I set them to purple to match the color of the new Emacs site design, which has all of the body links in that color.  It would be good to have them distinguished in the Reddit theme, though, because it's helpful to distinguish visited links.

Do you have any ideas?  I'd prefer to not simply use the traditional blue/purple, because then it wouldn't match the Emacs site anymore.  Maybe a lighter purple for visited links, or something like that?

**Comment by ajarara** [comment]
I'm sure a lighter purple would also look just fine, provided they are easy enough to distinguish.

Otherwise, why not #B11107
I lifted it off the Join the FSF button (or backdrop, they look the same), and it looks great IMO.

the other alternative for links taken off the site is #FFDE8F
but that is far too light to contrast with the background.

If neither of these work for you, can we field a discussion on the sub itself?
#B11107
![Red](http://i.imgur.com/9xzse6c.png)

 #FFDE8F
![Yellow](http://imgur.com/PxivHuu.png)

**Comment by alphapapa** [comment]
Yeah, the second one is definitely way too light.  

My preference would be to not use the red, because it stands out so much, that I think it wouldn't look good to be the main link color.  For example, the other red things on the page are the "(5 new)" and "Unsubscribe", which are supposed to be red to draw attention to them.

So I think a lighter purple would probably be a good solution.  It just needs to be the right shade so it's easily distinguished yet still just as readable against the background.  Do you want to experiment or should I?  :)

**Comment by ajarara** [comment]
How about this? Original link color is unchanged, with the addition of 

(in the following two images I visited Windows, Emacs, Emacs Wiki, and /r/spacemacs, along with the link in the OP)

``` css
a:visited {
    color: #C96EFF !important
}
```

here's the change
![the change](http://i.imgur.com/zczYQLw.png)

further, you could swap these, to maintain the same visited color people are used to. Here's how it looks:
![the change2](http://i.imgur.com/2Q0aLRs.png)
personally this 2nd change is a little confusing. i agree that a lighter purple -> clicked link is the way to go, it just looks more natural.

**Comment by alphapapa** [comment]
Hmm, that looks awfully pink to me.  :)  What do you think about this one?  `8a689f`  It's a desaturated version of the original color.

**Comment by ajarara** [comment]
That looks pretty good!

**Comment by alphapapa** [comment]
Thanks.  I'll send the mods a message letting them know there's an update available.

**Comment by ajarara** [comment]
They updated. Thanks!
